version: '2'
services: 
    postgres9:
        container_name: image-recognition-postgres-dev
        restart: always
        image: postgres:latest
        volumes:
            - ~/my-postgres/data:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: 123
            POSTGRES_USER: postgres
            PGDATA : /var/lib/postgresql/data
        ports:
            - 10000:5432


